[pytest]
pythonpath = .
testpaths = test_api_memes/tests
log_cli = true
log_cli_level = INFO
addopts = -p allure_pytest
markers =
    smoke: smoke tests
    regression: regression tests
    extended: extended tests
